# Generated by Django 3.2.20 on 2023-08-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='event_images/')),
            ],
        ),
    ]
