# Generated by Django 3.2.20 on 2023-11-03 22:52

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('files', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('material', models.CharField(blank=True, help_text='Max 500 words', max_length=500, null=True)),
                ('title', models.CharField(help_text='Max 500 words', max_length=500)),
                ('author', models.CharField(default='Fayaside Kolectif', help_text='Optional Field - Default author is Fayaside Kolectif', max_length=500)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='An overview of an exhibition', null=True)),
                ('slug', models.SlugField(blank=True, help_text='Optional', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
