# Generated by Django 3.2.20 on 2023-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_rename_singleexhibition_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
