# Generated by Django 3.2.20 on 2023-08-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='featured_order',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='password_required',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='post_medium',
        ),
    ]
