# Generated by Django 3.2.20 on 2023-08-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('event', 'Event'), ('article', 'Article')], max_length=200),
        ),
    ]
