# Generated by Django 3.2.20 on 2023-08-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_articles_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('spotify_podcast', models.URLField(blank=True, null=True)),
                ('apple_podcast', models.URLField(blank=True, null=True)),
                ('youtube_podcast', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
