# Generated by Django 3.2.20 on 2023-08-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230802_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontacts',
            name='address',
            field=models.CharField(blank=True, default='Default Address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='apple_podcast',
            field=models.URLField(blank=True, default='https://www.apple.com', null=True),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='contact_email',
            field=models.EmailField(blank=True, default='contact@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.facebook.com', null=True),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com', null=True),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='phone',
            field=models.CharField(blank=True, default='123-456-7890', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='spotify_podcast',
            field=models.URLField(blank=True, default='https://www.spotify.com', null=True),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='twitter',
            field=models.URLField(blank=True, default='https://www.twitter.com', null=True),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='youtube',
            field=models.URLField(blank=True, default='https://www.youtube.com', null=True),
        ),
        migrations.AlterField(
            model_name='sitecontacts',
            name='youtube_podcast',
            field=models.URLField(blank=True, default='https://www.youtube.com', null=True),
        ),
    ]
