# Generated by Django 3.2.20 on 2023-08-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230802_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_exibition',
            field=models.BooleanField(default=False),
        ),
    ]
