# Generated by Django 3.2.20 on 2023-08-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230815_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tagline',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='author',
            field=models.CharField(default='Fayaside Kolectif', max_length=500),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='material',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='slug',
            field=models.SlugField(blank=True, help_text='Optional', null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
