# Generated by Django 3.2.20 on 2023-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20230815_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Article', 'Article')], default='Article', max_length=100),
        ),
    ]
