# Generated by Django 3.2.20 on 2023-08-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontacts',
            name='paypal',
            field=models.URLField(blank=True, null=True),
        ),
    ]
