# Generated by Django 3.2.20 on 2023-11-03 15:38

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_sitecontacts_paypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='downloadable_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='author',
            field=models.CharField(default='Fayaside Kolectif', help_text='Optional Field - Default author is Fayaside Kolectif', max_length=500),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='An overview of an exhibition', null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='material',
            field=models.CharField(blank=True, help_text='Max 500 words', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(help_text='Max 500 words', max_length=500),
        ),
    ]
