# Generated by Django 3.2.20 on 2023-11-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20231103_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='downloadable_file',
            new_name='files',
        ),
    ]
