# Generated by Django 3.2.20 on 2023-11-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_downloadable_file_exhibition_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='files',
            new_name='file',
        ),
    ]
