# Generated by Django 3.2.20 on 2023-11-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_files_exhibition_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibition',
            old_name='file',
            new_name='files',
        ),
    ]
