# Generated by Django 3.2.20 on 2023-11-04 11:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_file_exhibition_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='files',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
