# Generated by Django 3.2.20 on 2023-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastsettings',
            name='podcast_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
